### PR TITLE
Conntrack support

### PR DESCRIPTION
**Pull request by marknl**
This PR adds support to manage the conntrack file.

It's a start. Currently it only supports helpers. Feel free to add more.

### CODE REVIEW

**Comment by duritong** [comment]
Nice thanks,

Any special reason that you named the define `shorewall::contrack::helper`, while all the other "helpers" do not use the name helper in them.

**Comment by marknl** [comment]
Hi,

Yeah.. this addition makes the use of CT:helper:name possible .. there are more like "NOTRACK|CT:notrack", that one might be names "shorewall::conntrack::notrack".

These are not on the same level as blacklist,rule,etc, but with conntrack (which IS on the same level as the previously mentioned).

Also, I noticed a typo "shorewall::contrack::helper" is missing an "n" in "contrack"

**Comment by duritong** [comment]
I still have a few shorewalls < 4.5 running :/ yeah I know... But I'll have to check how they deal with that file...

**Comment by duritong** [comment]
Let's see what happens...

**Comment by duritong** [comment]
Thanks, looks good...

**Comment by marknl** [comment]
You're welcome!

We're using this module a lot so I'll try to have the rest of the team also add their changes/additions to github.

**Comment by duritong** [comment]
Yes, please do so. Happy to accept improvements and bug fixes.

**Pull request merged**
